
- name: Instalar dependencias en CentOS 7
  yum:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - gcc
      - libffi-devel
      - python3-devel
      - openssl-devel
    state: present
  when: ansible_distribution == "CentOS"

#de momento lo instalo a mano porque da problemas en centos 7
#- name: Instalar la librería cryptography
#  pip:
#    name: cryptography
#    state: present
#    executable: pip3
