- name: Set hostname
  when: fix_hostname
  tags:
    - common
  ansible.builtin.hostname:
    name: "{{ ansible_fqdn }}"
  register: hostname_changed
    
- name: Instalar dependencias en Debian/Ubuntu de ansible
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - libssl-dev
      - libffi-dev
      - build-essential
    state: present
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Instalar cryptography desde apt
  ansible.builtin.apt:
    name: python3-cryptography
    state: present

- name: Set timezone to Etc/UTC
  tags:
    - timezone
  community.general.timezone:
    name: Etc/UTC

- name: Add keys
  tags:
    - keys
  ansible.posix.authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{item.type}} {{ item.key }} {{item.name}}"
  loop: "{{ ssh_keys }}"

- name: Update Etc/hosts with hostname
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    regexp: "^127.0.1.1"
  when: fix_hostname and hostname_changed is defined and hostname_changed.changed

- name: Install qemu-guest-agent
  package:
    name: qemu-guest-agent
    state: present
  when: not machine_dedicated

- name: Enable qemu guest agent
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
  ignore_errors: true
  when: not machine_dedicated

- name: Ensure Cloud init does not fuck it off all
  when: cloudinit.disabled and not machine_dedicated
  template:
    dest: /etc/cloud/cloud.cfg.d/99-teamsquad-config.cfg
    src: 99-teamsquad-config.cfg
  when: not machine_dedicated

- name: Disable unattended-upgrades.service
  service:
    name: unattended-upgrades.service
    state: stopped
    enabled: no
  when: ansible_distribution == 'Ubuntu'